---

- name: install openvpn
  become: true
  pacman: name=openvpn
  tags: vpn

- name: test if openvpn-update-systemd-resolved is installed
  become: true
  stat: path=/etc/openvpn/scripts/update-systemd-resolved
  register: openvpnupdatesystemdresolved
  tags: vpn

- name: install openvpn-update-systemd-resolved
  become: false
  command: /usr/bin/yay --noconfirm -S openvpn-update-systemd-resolved
  when: openvpnupdatesystemdresolved.stat.exists == False
  tags: vpn

- name: test if config is present
  become: true
  stat: path="/etc/openvpn/client/{{ item }}.conf"
  register: openvpn_conf
  with_items: "{{ openvpn }}"
  tags: vpn

- name: copy openvpn config
  become: true
  copy:
    src: "vpn/{{ item.item }}_openvpn.vault"
    dest: "/etc/openvpn/{{ item.item }}_openvpn.tar.gz"
  when: item.stat.exists == False
  with_items: "{{ openvpn_conf.results }}"
  tags: vpn

# stop point
#- meta: end_play

- name: copy and install openvpn config
  become: true
  unarchive: src="/etc/openvpn/{{ item.item }}_openvpn.tar.gz" dest=/etc/openvpn/client/ remote_src=yes
  when: item.stat.exists == False
  with_items: "{{ openvpn_conf.results }}"
  tags: vpn

- name: delete the archive
  become: true
  file: path="/etc/openvpn/{{ item.item }}_openvpn.tar.gz" state=absent
  with_items: "{{ openvpn_conf.results }}"
  tags: vpn

- name: assume systemd-resolved is started
  become: true
  systemd: name="systemd-resolved" enabled=yes state=started
  tags: vpn

- name: enable openvpn vpn service
  become: true
  systemd: name="openvpn-client@{{ item.item }}" state=started
  with_items: "{{ openvpn_conf.results }}"
  tags: vpn

