---

# packages
- import_tasks: gui_packages.yml
  tags: pkg,aur

- name: configure keyboard
  become: true
  copy: src=00-keyboard-mac-azerty.conf dest=/etc/X11/xorg.conf.d/00-keyboard.conf
  when: keyboard|default(False) == 'mac-azerty'
  tags: keyboard

- name: has bluetooth ?
  shell: "lsusb | grep -i bluetooth"
  register: has_bluetooth
  changed_when: has_bluetooth is success
  ignore_errors: yes
  tags: bluetooth

- name: install bluetooth
  become: true
  pacman: name=bluez,bluez-utils,dbus,blueman,blueberry state=present
  when: has_bluetooth is success
  tags: bluetooth

- name: up bluetooth device on start
  become: true
  copy: src=10-local.rules dest=/etc/udev/rules.d/10-local.rules
  when: has_bluetooth is success
  tags: bluetooth

- name: enable bluetooth on start
  become: true
  service: name=bluetooth state=started enabled=yes
  when: has_bluetooth is success
  tags: bluetooth

#- name: configure slim
#  become: true
#  lineinfile:
#    dest: /etc/slim.conf
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#    backrefs: yes
#  with_items:
#    - { regexp: '^# sessionstart_cmd', line: 'sessionstart_cmd    /usr/bin/sessreg -a -l $DISPLAY %user' }
#    - { regexp: '^# sessionstop_cmd', line: 'sessionstop_cmd    /usr/bin/sessreg -d -l $DISPLAY %user' }
#    - { regexp: '^current_theme.*default$', line: 'current_theme  archlinux-solarized' }
#
#- name: install slim theme
#  become: true
#  git: repo=https://github.com/tyjak/slim-theme-archlinux-solarized.git dest=/usr/share/slim/themes/archlinux-solarized
#  
#- name: enable slim at boot
#  become: true
#  service: name=slim enabled=yes
